# Generated by Django 3.1.3 on 2020-12-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='分类')),
                ('code', models.IntegerField(verbose_name='编码')),
                ('value', models.CharField(max_length=30, verbose_name='编码值')),
                ('order_number', models.IntegerField(verbose_name='顺序号，代表显示优先级')),
                ('comment', models.CharField(max_length=30, verbose_name='备注')),
            ],
            options={
                'db_table': 't_sys_code',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='菜单名称')),
                ('code', models.CharField(default='1', max_length=30, unique=True, verbose_name='菜单编号')),
                ('parent_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='父级菜单')),
                ('url', models.CharField(blank=True, max_length=30, null=True, verbose_name='URL')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='菜单级别')),
                ('is_Enabled_tsc', models.IntegerField(verbose_name='是否启用')),
            ],
            options={
                'db_table': 't_sys_menu',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('note', models.CharField(blank='true', max_length=100, null='true', verbose_name='备注')),
            ],
            options={
                'db_table': 't_sys_role',
            },
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='', max_length=30, verbose_name='用户名')),
                ('u_pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('u_status_tsc', models.IntegerField(verbose_name='账号状态')),
                ('apply_date', models.DateTimeField(blank=True, null=True, verbose_name='申请日期')),
                ('approvel_date', models.DateTimeField(blank=True, null=True, verbose_name='审批日期')),
                ('chinese_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='中文名称')),
                ('identity_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('telephone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('landline', models.CharField(max_length=15, null=True, verbose_name='固定电话')),
                ('wechanumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信号')),
                ('email', models.CharField(default='123456789', max_length=30, null=True, verbose_name='邮箱')),
                ('appid', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信验证应用标识')),
                ('lastlogin_date', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('system_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sm.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='认证用户')),
            ],
            options={
                'db_table': 't_sys_user',
            },
        ),
        migrations.CreateModel(
            name='role_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.menu', verbose_name='菜单id')),
                ('system_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.role', verbose_name='角色id')),
            ],
            options={
                'db_table': 't_sys_role_menu',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='menu_info',
            field=models.ManyToManyField(through='sm.role_menu', to='sm.menu', verbose_name='菜单信息'),
        ),
    ]
