# Generated by Django 3.1.3 on 2020-11-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evaluate',
            fields=[
                ('evaluateId', models.CharField(db_column='evaluate_id', max_length=32, primary_key=True, serialize=False)),
                ('userId', models.CharField(db_column='user_id', max_length=32, verbose_name='用户主键')),
                ('applyNum', models.CharField(db_column='apply_num', max_length=12, verbose_name='申请单号')),
                ('applyDate', models.DateField(db_column='apply_date', max_length=6, verbose_name='申请日期')),
                ('evaluateType', models.IntegerField(db_column='evaluate_type', null=True, verbose_name='结算类型：1、货款，2、运费')),
                ('actualEvaluateAmount', models.FloatField(db_column='actual_evaluate_amount', verbose_name='本次实结算金额')),
                ('paymentAmount', models.FloatField(db_column='payment_amount', verbose_name='贷款金额')),
                ('freightAmount', models.FloatField(db_column='freight_amount', verbose_name='运费金额')),
                ('fineAmount', models.FloatField(db_column='fine_amount', verbose_name='罚款金额')),
                ('liquidatedDamagesAmount', models.FloatField(db_column='liquidated_damages_amount', verbose_name='违约金')),
                ('evaluateExplain', models.CharField(db_column='evaluate_explain', max_length=300, verbose_name='说明')),
                ('evaluatePeopleId', models.CharField(db_column='evaluate_people_id', max_length=32, verbose_name='结算人主键,当前登录人')),
                ('evaluatePeople', models.CharField(db_column='evaluate_people', max_length=20, verbose_name='结算人主键,当前登录人')),
                ('evaluateFinish_time', models.DateField(db_column='evaluate_finish_time', max_length=6, verbose_name='结算完成时间')),
                ('evaluateState', models.IntegerField(db_column='evaluate_state', null=True, verbose_name='状态：1、新建，2、流转，3、完成')),
            ],
            options={
                'db_table': 't_fm_evaluate',
            },
        ),
        migrations.CreateModel(
            name='evaluateInfo',
            fields=[
                ('evaluateInfoId', models.CharField(db_column='evaluate_info_id', max_length=32, primary_key=True, serialize=False)),
                ('evaluateId', models.CharField(db_column='evaluate_id', max_length=32, verbose_name='结算申请单主键')),
                ('orderId', models.CharField(db_column='order_id', max_length=32, verbose_name='订单主键：关联已完成未结算的订单')),
            ],
            options={
                'db_table': 't_fm_evaluateInfo',
            },
        ),
    ]
