# Generated by Django 3.1.3 on 2020-11-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='companyId',
            field=models.CharField(db_column='company_id', max_length=32, null=True, verbose_name='公司ID'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', max_length=6, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='createUserId',
            field=models.CharField(db_column='create_user_id', max_length=32, null=True, verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='delFlag',
            field=models.IntegerField(db_column='del_flag', null=True, verbose_name='是否删除：1已删除，2未删除'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='deptId',
            field=models.CharField(db_column='dept_id', max_length=32, null=True, verbose_name='机构ID'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='updateTime',
            field=models.DateTimeField(db_column='update_time', max_length=6, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='updateUserId',
            field=models.CharField(db_column='update_user_id', max_length=32, null=True, verbose_name='更新人ID'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='companyId',
            field=models.CharField(db_column='company_id', max_length=32, null=True, verbose_name='公司ID'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', max_length=6, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='createUserId',
            field=models.CharField(db_column='create_user_id', max_length=32, null=True, verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='delFlag',
            field=models.IntegerField(db_column='del_flag', null=True, verbose_name='是否删除：1已删除，2未删除'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='deptId',
            field=models.CharField(db_column='dept_id', max_length=32, null=True, verbose_name='机构ID'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='updateTime',
            field=models.DateTimeField(db_column='update_time', max_length=6, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='evaluateinfo',
            name='updateUserId',
            field=models.CharField(db_column='update_user_id', max_length=32, null=True, verbose_name='更新人ID'),
        ),
    ]
