# Generated by Django 3.1.3 on 2020-11-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0002_auto_20201121_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluate',
            old_name='evaluateFinish_time',
            new_name='evaluateFinishTime',
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='delFlag',
            field=models.IntegerField(db_column='del_flag', null=True, verbose_name='是否删除·：1已删除，2未删除'),
        ),
    ]
