# Generated by Django 3.1.3 on 2020-11-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0003_auto_20201122_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='evaluate',
            new_name='fmEvaluate',
        ),
        migrations.RenameModel(
            old_name='evaluateInfo',
            new_name='fmEvaluateInfo',
        ),
    ]
