# Generated by Django 3.1.3 on 2020-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0004_auto_20201123_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmevaluate',
            name='actualEvaluateAmount',
            field=models.FloatField(db_column='actual_evaluate_amount', null=True, verbose_name='本次实结算金额'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='evaluateExplain',
            field=models.CharField(db_column='evaluate_explain', max_length=300, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='evaluateFinishTime',
            field=models.DateField(db_column='evaluate_finish_time', max_length=6, null=True, verbose_name='结算完成时间'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='evaluatePeople',
            field=models.CharField(db_column='evaluate_people', max_length=20, null=True, verbose_name='结算人主键,当前登录人'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='evaluatePeopleId',
            field=models.CharField(db_column='evaluate_people_id', max_length=32, null=True, verbose_name='结算人主键,当前登录人'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='fineAmount',
            field=models.FloatField(db_column='fine_amount', null=True, verbose_name='罚款金额'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='freightAmount',
            field=models.FloatField(db_column='freight_amount', null=True, verbose_name='运费金额'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='liquidatedDamagesAmount',
            field=models.FloatField(db_column='liquidated_damages_amount', null=True, verbose_name='违约金'),
        ),
        migrations.AlterField(
            model_name='fmevaluate',
            name='paymentAmount',
            field=models.FloatField(db_column='payment_amount', null=True, verbose_name='贷款金额'),
        ),
    ]
